### ISSUE TITLE
Getting a TypeError when running Vagrant on Windows 10

### ISSUE THREAD

**Issue by tomgross** [puzzle/puppet-openshift3#1]
Trying the recipe with Windows 10 as Host gives an error:

```
$ vagrant up origin-master
C:/Users/Tom/puppet-openshift3/.vagrantplugins:9:in `system': no implicit conversion from nil to integer (TypeError)
        from C:/Users/Tom/puppet-openshift3/.vagrantplugins:9:in `block in <top (required)>'
        from C:/Users/Tom/puppet-openshift3/.vagrantplugins:7:in `each'
        from C:/Users/Tom/puppet-openshift3/.vagrantplugins:7:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:172:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:172:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:165:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:165:in `<main>'
```
Version of Vagrant: 1.7.4
Version of VirtualBox 5.0.8

**Comment by dtschan** [comment]
Fixed by pull request #3. Thanks to @tomgross.
